version: "3.7"
services:
    nginx:
        container_name: sgbg-nginx
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        depends_on:
            - server
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/nginx/conf:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        restart: always
    certbot:
        container_name: sgbg-certbot
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    # mysql:
    #     container_name: sgbg-mysql
    #     image: mysql:5.7
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./data/mysql:/var/lib/mysql
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=tldrmfqjdrmf
    #         - MYSQL_DATABASE=sgbg
    #     command:
    #         - --character-set-server=utf8
    #         - --collation-server=utf8_general_ci
    #     restart: always
    redis:
        container_name: sgbg-redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: on-failure
    server:
        container_name: sgbg-server
        depends_on:
            # - mysql
            - redis
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - 8080:8080
        restart: on-failure
